### ISSUE TITLE
Just a couple of small issues

### ISSUE THREAD

**Issue by DantheChef** [tbrittain/SmbExplorerCompanion#118]
This is on Version 1.1.0.
- For the career stats on the player's page, it looks like OPS+ is just an average of the regular season and postseason numbers. It looks like all of the rest of the advanced stats are averaged correctly. 
![image](https://github.com/tbrittain/SmbExplorerCompanion/assets/26890375/6cf7a65a-bf5b-4e40-a946-0a42622113b0)
- For both career pitching and batting, the advanced stats can't be sorted, like ERA-, OPS+. You can sort on the season stats pages. 
![image](https://github.com/tbrittain/SmbExplorerCompanion/assets/26890375/ee0a907c-20ee-41e1-9661-78aed8106650)

**Comment by tbrittain** [comment]
Regarding your first point, this is true - I will look into what it'll take to make that a more accurate indicator of the career OPS+. It'll likely just take weighing that number in the average according to the #PA the player had with that OPS+ (which should fix the issue with the few #PA during the postseason being weighed the same)

And regarding your second point, this is something I plan to fix with the next release: #50 . I had some concerns with how to sort by those numbers for the career screen, since it's easier to do so on the season screen when we can just omit the unqualified players from that sort order. I'll need to think on the best way to do this for the career

**Comment by tbrittain** [comment]
Based on the way that the career data is being pulled, it should correct the career OPS+ value on the player page, as well as the career batting grids. I'll make sure this is corrected for ERA- (which I need to rename to ERA+) as well

**Comment by tbrittain** [comment]
Closing this for now as the OPS+/ERA+/FIP+ career average will have been fixed in v1.1.2, releasing shortly
